### ISSUE TITLE
Cassandra 0.7 API does not work with thrift 0.2

### ISSUE THREAD

**Issue by jpartogi** [cassandra-rb/cassandra#56]
I pull out fauna/cassandra gem 0.10.0 from github.

I then tried to get a value from cassandra as such.

irb(main):002:0> require 'cassandra/0.7'
=> true
irb(main):003:0> client = Cassandra.new('Keyspace1', '127.0.0.1:9160')
=> #<Cassandra:70286805872140, @keyspace="Keyspace1", @schema={}, @servers=["127.0.0.1:9160"]>
irb(main):004:0> client.insert(:Standard1, "5", {'screen_name' => "buttonscat"})
=> nil
irb(main):006:0> client.get(:Standard1, "5", 'screen_name')
NoMethodError: undefined method `multiget' for #<ThriftClient:0x7fd9d82e5270>
    from /home/jpartogi/.rvm/gems/ruby-1.8.7-p302/gems/cassandra-0.10.0/lib/cassandra/0.7/protocol.rb:53:in`_multiget'
    from /home/jpartogi/.rvm/gems/ruby-1.8.7-p302/gems/cassandra-0.10.0/lib/cassandra/cassandra.rb:198:in `multi_get'
    from /home/jpartogi/.rvm/gems/ruby-1.8.7-p302/gems/cassandra-0.10.0/lib/cassandra/cassandra.rb:189:in`get'
    from (irb):6
    from :0
irb(main):007:0>

It turns out that the gem is still relying on thrift < 0.2.5 as can be seen on cassandra.rb.

**Comment by ryanking** [comment]
upgraded to 0.9.0 to use thrift 0.5.0
